"""
execute.py — Auto-generated by the DataQA Agent
================================================
This file is rewritten every time the agent executes a function.
It is a complete, runnable Python script that reproduces ALL
function calls made during the current session in order.

Dataset: <path to your dataset file>
Shape  : unknown
Columns: unknown
"""

import pandas as pd
import numpy as np
import json
import os
import sys
from typing import Dict, Any, List, Optional

# ─────────────────────────────────────────────────────────────────
# DATASET LOADING
# Replace the path below with the actual path to your dataset.
# ─────────────────────────────────────────────────────────────────
DATASET_PATH = os.path.join(os.path.dirname(__file__), "data/VIL_P2_agentdata.xlsx")

def load_dataset(path: str) -> pd.DataFrame:
    """Load dataset from CSV or Excel, auto-detecting format."""
    if path.endswith('.xlsx') or path.endswith('.xls'):
        return pd.read_excel(path)
    return pd.read_csv(path)

df = load_dataset(DATASET_PATH)
print(f"✅ Dataset loaded: {len(df)} rows × {len(df.columns)} columns")

# No functions have been executed in this session yet.

if __name__ == "__main__":
    print("No functions to run.")
