import pandas as pd

def load_css(file_name="style.css"):
    with open(file_name, "r", encoding="utf-8") as f:
        # Add custom overrides for Streamlit to prevent scrollbars and hide default chrome
        css = f.read()
        css += """
        /* Streamlit overrides */
        header {visibility: hidden;}
        #MainMenu {visibility: hidden;}
        footer {visibility: hidden;}
        .block-container {
            padding-top: 2rem;
            padding-bottom: 2rem;
            max-width: 1400px;
        }
        /* Make Streamlit buttons match our style somewhat */
        div.stButton > button:first-child {
            background-color: var(--accent);
            color: #000;
            border: none;
            border-radius: var(--radius);
            font-family: var(--sans);
            font-weight: 500;
            transition: all 0.2s;
        }
        div.stButton > button:first-child:hover {
            background-color: #4fb8ff;
            transform: translateY(-1px);
            box-shadow: 0 8px 24px rgba(26,159,255,0.3);
            color: #000;
        }
        
        /* Style text areas */
        .stTextArea textarea {
            background-color: var(--surface2) !important;
            color: var(--text-bright) !important;
            border: 1px solid var(--border) !important;
            border-radius: var(--radius) !important;
            font-family: var(--mono) !important;
        }
        .stTextArea textarea:focus {
            border-color: var(--accent) !important;
            box-shadow: 0 0 0 1px var(--accent) !important;
        }
        """
        return f"<style>\n{css}\n</style>"

def get_nav_html():
    return """
    <nav style="margin-top: -2rem; margin-bottom: 2rem;">
      <div class="nav-logo">
        <div class="dot"></div>
        DataQA
      </div>
      <div class="nav-status">
        <div class="status-dot"></div>
        Agents online
      </div>
    </nav>
    """

def get_header_html(title_word1="New", title_word2="Quality", title_word3="Analysis", step_text="step 01 — configure run", side_text="🔒 LLMs access <strong>only your prompt</strong><br>Your dataset stays local"):
    return f"""
    <div class="section-header">
      <div>
        <div class="section-meta">{step_text}</div>
        <div class="section-title">{title_word1} <span>{title_word2}</span> {title_word3}</div>
      </div>
      <div style="font-size:11px; color:var(--text-dim); text-align:right; line-height:1.8;">
        {side_text}
      </div>
    </div>
    """

def get_pipeline_html(active_step=1):
    def node_class(step):
        if step < active_step: return "pipeline-node done"
        if step == active_step: return "pipeline-node active"
        return "pipeline-node"
        
    def arrow_class(step):
        if step < active_step: return "pipeline-arrow active" # flowing to next
        return "pipeline-arrow"

    return f"""
    <div class="card">
      <div class="card-label">Agent Pipeline</div>
      <div class="pipeline" style="padding:10px 0;">
        <div class="{node_class(1)}" id="node-user">
          <div class="pipeline-node-icon">👤</div>
          <div class="pipeline-node-label">User Input</div>
        </div>
        <div class="{arrow_class(1)}" id="arr-1"></div>
        <div class="{node_class(2)}" id="node-reasoning">
          <div class="pipeline-node-icon">🧠</div>
          <div class="pipeline-node-label">Reasoning Agent</div>
        </div>
        <div class="{arrow_class(2)}" id="arr-2"></div>
        <div class="{node_class(3)}" id="node-orchestrator">
          <div class="pipeline-node-icon">⚙️</div>
          <div class="pipeline-node-label">Orchestrator</div>
        </div>
        <div class="{arrow_class(3)}" id="arr-3"></div>
        <div class="{node_class(4)}" id="node-functions">
          <div class="pipeline-node-icon">📦</div>
          <div class="pipeline-node-label">Functions DB</div>
        </div>
        <div class="{arrow_class(4)}" id="arr-4"></div>
        <div class="{node_class(5)}" id="node-report">
          <div class="pipeline-node-icon">📋</div>
          <div class="pipeline-node-label">QA Report</div>
        </div>
      </div>
    </div>
    """

def get_metric_cards_html(score, missing_pct, duplicates_pct, outliers_count):
    return f"""
    <div class="results-header" style="margin-bottom: 0;">
      <div class="results-score">
        <div class="score-num">{score}</div>
        <div class="score-label">Quality</div>
      </div>
      <div class="results-info">
        <div class="results-title">Analysis Complete</div>
        <div class="results-meta" style="margin-top:4px;">
          Generated by Reasoning Agent
        </div>
      </div>
      <div style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:8px; min-width:200px;">
        <div class="metric-card">
          <div class="metric-value {'warn' if missing_pct > 0 else 'good'}">{missing_pct}%</div>
          <div class="metric-label">Missing</div>
        </div>
        <div class="metric-card">
          <div class="metric-value {'warn' if duplicates_pct > 0 else 'good'}">{duplicates_pct}%</div>
          <div class="metric-label">Duplicates</div>
        </div>
        <div class="metric-card">
          <div class="metric-value {'bad' if outliers_count > 0 else 'good'}">{outliers_count}</div>
          <div class="metric-label">Outliers</div>
        </div>
      </div>
    </div>
    """

def get_issue_html(title, body, level="warning"):
    """level can be 'critical', 'warning', or 'info'"""
    badge_class = level
    if level == "info": badge_class = "new"
    
    return f"""
    <div class="issue-item {level}">
      <div class="issue-title">
        <span class="badge {badge_class}">{level.capitalize()}</span>
        {title}
      </div>
      <div class="issue-body">
        {body}
      </div>
    </div>
    """
