"""
Execute Writer
==============
Manages `execute.py` — the live, always-runnable Python script that contains
every function executed during the current agent session, complete with:

  • All import statements
  • Dataset loading boilerplate
  • Full source code of each function (original or auto-corrected)
  • An `if __name__ == "__main__"` block that calls every function in order
    and prints results

The file is rewritten atomically each time a function is added so it stays
valid Python at every point in time.

Public API
----------
append_function_to_execute(function_name, function_code, target_column,
                            function_description, df)
    → Called after a NEW (Group 4) function is generated and verified.

append_existing_function_call(function_name, function_code, params,
                              function_description, df)
    → Called when an EXISTING (Group 1-3) function is invoked with params.

reset_execute_file()
    → Called at the start of each new analysis run to clear old entries.

set_dataset_path(path)
    → Called from app.py when a file is uploaded, so execute.py loads the right file.
"""

from __future__ import annotations

import json
import os
import textwrap
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

EXECUTE_FILE = "execute.py"

# ---------------------------------------------------------------------------
# In-memory session state  (module-level, lives for the lifetime of the process)
# ---------------------------------------------------------------------------

@dataclass
class _FunctionEntry:
    kind: str                   # "generated" | "existing"
    function_name: str
    function_code: str          # Full def block
    target_column: str          # For generated (series-based) functions
    params: Dict[str, Any]      # For existing (df+params) functions
    function_description: str
    column_dtype: str = "unknown"
    column_sample: str = "[]"


_SESSION_ENTRIES: List[_FunctionEntry] = []
_DATASET_CSV_PATH: str = ""       # Set on first call so execute.py knows where to load data from
_DATASET_COLUMNS: List[str] = []
_DATASET_SHAPE: str = ""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _capture_df_meta(df) -> None:
    """Cache dataset metadata for the execute.py header."""
    global _DATASET_COLUMNS, _DATASET_SHAPE
    try:
        import pandas as pd
        _DATASET_COLUMNS = list(df.columns)
        _DATASET_SHAPE   = f"{len(df)} rows × {len(df.columns)} columns"
    except Exception:
        pass


def _column_info(df, column: str) -> tuple[str, str]:
    """Return (dtype_str, sample_str) for a column."""
    try:
        s = df[column]
        dtype_str  = str(s.dtype)
        sample_str = json.dumps(s.dropna().head(5).tolist(), default=str)
        return dtype_str, sample_str
    except Exception:
        return "unknown", "[]"


# ---------------------------------------------------------------------------
# File renderer
# ---------------------------------------------------------------------------

def _render_execute_file() -> str:
    """Build the full content of execute.py from current _SESSION_ENTRIES."""

    lines: List[str] = []

    # ── Header ──────────────────────────────────────────────────────────────
    lines += [
        '"""',
        "execute.py — Auto-generated by the DataQA Agent",
        "================================================",
        "This file is rewritten every time the agent executes a function.",
        "It is a complete, runnable Python script that reproduces ALL",
        "function calls made during the current session in order.",
        "",
        f"Dataset: {_DATASET_CSV_PATH or '<path to your dataset file>'}",
        f"Shape  : {_DATASET_SHAPE or 'unknown'}",
        f"Columns: {', '.join(_DATASET_COLUMNS) or 'unknown'}",
        '"""',
        "",
    ]

    # ── Imports ──────────────────────────────────────────────────────────────
    lines += [
        "import pandas as pd",
        "import numpy as np",
        "import json",
        "import os",
        "import sys",
        "from typing import Dict, Any, List, Optional",
        "",
    ]

    # ── Dataset loader ───────────────────────────────────────────────────────
    load_path = _DATASET_CSV_PATH or "data/sample_faulty_data.csv"
    lines += [
        "# ─────────────────────────────────────────────────────────────────",
        "# DATASET LOADING",
        "# Replace the path below with the actual path to your dataset.",
        "# ─────────────────────────────────────────────────────────────────",
        f'DATASET_PATH = os.path.join(os.path.dirname(__file__), "{load_path}")',
        "",
        "def load_dataset(path: str) -> pd.DataFrame:",
        '    """Load dataset from CSV or Excel, auto-detecting format."""',
        "    if path.endswith('.xlsx') or path.endswith('.xls'):",
        "        return pd.read_excel(path)",
        "    return pd.read_csv(path)",
        "",
        "df = load_dataset(DATASET_PATH)",
        f'print(f"✅ Dataset loaded: {{len(df)}} rows × {{len(df.columns)}} columns")',
        "",
    ]

    if not _SESSION_ENTRIES:
        lines += [
            "# No functions have been executed in this session yet.",
            "",
            'if __name__ == "__main__":',
            '    print("No functions to run.")',
            "",
        ]
        return "\n".join(lines)

    # ── Function definitions ─────────────────────────────────────────────────
    lines += [
        "# ─────────────────────────────────────────────────────────────────",
        "# FUNCTION DEFINITIONS",
        "# ─────────────────────────────────────────────────────────────────",
        "",
    ]

    seen_functions = set()
    for entry in _SESSION_ENTRIES:
        if entry.function_name not in seen_functions:
            seen_functions.add(entry.function_name)
            lines += [
                f"# {'-' * 60}",
                f"# Function : {entry.function_name}",
                f"# Kind     : {entry.kind}",
                f"# Desc     : {entry.function_description}",
                f"# {'-' * 60}",
            ]
            # Dedent the function code in case it was indented
            clean_code = textwrap.dedent(entry.function_code).strip()
            lines += clean_code.splitlines()
            lines += ["", ""]

    # ── Main execution block ─────────────────────────────────────────────────
    lines += [
        "# ─────────────────────────────────────────────────────────────────",
        "# EXECUTION  (run all functions in the order they were invoked)",
        "# ─────────────────────────────────────────────────────────────────",
        "",
        "def run_all(df: pd.DataFrame) -> Dict[str, Any]:",
        '    """Runs every function executed during the agent session."""',
        "    results: Dict[str, Any] = {}",
        "",
    ]

    for i, entry in enumerate(_SESSION_ENTRIES, 1):
        call_label = f"call_{i:02d}_{entry.function_name}"
        lines += [
            f"    # ── Call {i}: {entry.function_name} ──",
        ]
        if entry.kind == "generated":
            # series-based: def fn(series) -> dict
            lines += [
                f"    try:",
                f'        series = df["{entry.target_column}"]',
                f"        result_{call_label} = {entry.function_name}(series)",
                f'        print(f"  [{i}] {entry.function_name}({entry.target_column!r}): {{result_{call_label}}}")',
                f'        results["{call_label}"] = result_{call_label}',
                f"    except Exception as _e:",
                f'        print(f"  [{i}] {entry.function_name} FAILED: {{_e}}")',
                f'        results["{call_label}"] = {{"error": str(_e)}}',
                f"",
            ]
        else:
            # df-based with params: def fn(df, params) -> dict
            params_repr = json.dumps(entry.params, default=str)
            lines += [
                f"    try:",
                f"        _params = {params_repr}",
                f"        result_{call_label} = {entry.function_name}(df, _params)",
                f'        print(f"  [{i}] {entry.function_name}(params={params_repr}): {{result_{call_label}}}")',
                f'        results["{call_label}"] = result_{call_label}',
                f"    except Exception as _e:",
                f'        print(f"  [{i}] {entry.function_name} FAILED: {{_e}}")',
                f'        results["{call_label}"] = {{"error": str(_e)}}',
                f"",
            ]

    lines += [
        "    return results",
        "",
        "",
        'if __name__ == "__main__":',
        '    print("\\n" + "=" * 60)',
        '    print("  DataQA Agent — Session Execution Replay")',
        '    print("=" * 60 + "\\n")',
        "    all_results = run_all(df)",
        '    print("\\n" + "─" * 60)',
        '    print(f"  ✅ {len(all_results)} function calls completed.")',
        '    print("─" * 60)',
        "    print(json.dumps(all_results, indent=2, default=str))",
        "",
    ]

    return "\n".join(lines)


def _write_file() -> None:
    """Render and atomically write execute.py."""
    content = _render_execute_file()
    tmp_path = EXECUTE_FILE + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp_path, EXECUTE_FILE)
    print(f"📝  execute.py updated ({len(_SESSION_ENTRIES)} function entries)")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def set_dataset_path(path: str) -> None:
    """
    Record the uploaded dataset filename so execute.py loads the right file.
    Call this from app.py immediately after the file is uploaded.
    """
    global _DATASET_CSV_PATH
    _DATASET_CSV_PATH = path


def reset_execute_file(dataset_path: str = "", df=None) -> None:
    """
    Call this at the start of every new analysis run.
    Clears the in-memory list and rewrites execute.py from scratch.
    """
    global _SESSION_ENTRIES, _DATASET_CSV_PATH
    _SESSION_ENTRIES = []
    _DATASET_CSV_PATH = dataset_path
    if df is not None:
        _capture_df_meta(df)
    _write_file()


def append_function_to_execute(
    function_name: str,
    function_code: str,
    target_column: str,
    function_description: str,
    df,
) -> None:
    """
    Append a newly generated (and Code-Tester-verified) function to execute.py.
    Called by `generate_and_test_custom_function` after a successful save.
    """
    global _SESSION_ENTRIES
    _capture_df_meta(df)
    dtype_str, sample_str = _column_info(df, target_column)

    entry = _FunctionEntry(
        kind="generated",
        function_name=function_name,
        function_code=function_code,
        target_column=target_column,
        params={},
        function_description=function_description,
        column_dtype=dtype_str,
        column_sample=sample_str,
    )
    _SESSION_ENTRIES.append(entry)
    _write_file()


def append_existing_function_call(
    function_name: str,
    function_code: str,
    params: Dict[str, Any],
    function_description: str,
    df,
) -> None:
    """
    Append a call to an existing (approved) function to execute.py.
    Called by `execute_existing_function_with_params` after a successful execution.
    """
    global _SESSION_ENTRIES
    _capture_df_meta(df)
    target_col = params.get("target_column") or params.get("column", "")

    entry = _FunctionEntry(
        kind="existing",
        function_name=function_name,
        function_code=function_code,
        target_column=target_col,
        params=params,
        function_description=function_description,
    )
    _SESSION_ENTRIES.append(entry)
    _write_file()
