import pandas as pd
from typing import Any, Dict, List, Optional
from langchain_core.tools import tool
import json

# Global reference to the current dataframe for tools to use
_CURRENT_DF = None

def set_current_df(df: pd.DataFrame):
    """Stores the active dataframe so the tools can query against it."""
    global _CURRENT_DF
    _CURRENT_DF = df

@tool
def generate_and_test_custom_function(function_name: str, code: str, target_column: str, function_description: str = "Autogenerated custom function.") -> str:
    """
    Generates a new data quality python function, automatically tests and fixes it
    using the Code Testing Agent, then saves the verified code to the database.

    The python function MUST take a single argument `series` (which is a pd.Series)
    and return a Dictionary of stats or findings.
    You must provide the raw python code for the function in the `code` argument.
    You must provide a `function_description` briefly explaining what this check does.

    The Code Testing Agent will:
    1. Perform static (syntax/scope) checks
    2. Execute the function on the real dataset column
    3. If it fails, automatically send the error + code to the LLM for bug-fixing
    4. Retry up to 3 times until the function works correctly

    The VERIFIED (possibly auto-corrected) function code is saved to SQLite with
    "approved_by_team=False" (Group 4) and the result is returned.
    """
    global _CURRENT_DF
    if _CURRENT_DF is None:
        return "Error: No dataframe loaded."

    if target_column not in _CURRENT_DF.columns:
        return json.dumps({
            "success": False,
            "error": f"Column '{target_column}' is not valid. Available columns: {list(_CURRENT_DF.columns)}"
        })

    # ── Run the Code Testing Agent ─────────────────────────────────────────
    from agents.code_tester import test_and_fix_function
    test_result = test_and_fix_function(
        function_name=function_name,
        code=code,
        target_column=target_column,
        df=_CURRENT_DF,
        verbose=True,
    )

    if not test_result.success:
        return json.dumps({
            "success": False,
            "function_name": function_name,
            "target_column": target_column,
            "code_tester_attempts": test_result.attempts,
            "error": test_result.error,
            "test_log": [
                {"attempt": e["attempt"], "phase": e["phase"], "ok": e.get("success", False)}
                for e in test_result.test_log
            ],
            "message": (
                "The Code Testing Agent could not produce a working version of this function. "
                "Please review the error and try again with a different approach."
            ),
        }, default=str)

    # ── Save the VERIFIED code to database ────────────────────────────────
    import sqlite3
    import datetime
    db_path = "database/app.db"
    now = datetime.datetime.now().isoformat()
    final_code = test_result.final_code  # may differ from original if auto-fixed

    try:
        with sqlite3.connect(db_path, timeout=10.0) as conn:
            cursor = conn.cursor()
            cursor.execute('''
                INSERT INTO data_quality_functions
                (function_name, function_code, function_description, function_group, approved_by_team, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            ''', (
                function_name,
                final_code,
                function_description,
                4,      # Group 4 — Agent Generated
                False,  # Pending team approval
                now,
                now,
            ))
    except sqlite3.IntegrityError:
        return json.dumps({
            "success": False,
            "error": f"Function name conflict: '{function_name}' already exists in the database. "
                     "Please generate the function again using a UNIQUE name.",
        })

    # ── Update execute.py to include the new function ─────────────────────
    try:
        from agents.execute_writer import append_function_to_execute
        append_function_to_execute(
            function_name=function_name,
            function_code=final_code,
            target_column=target_column,
            function_description=function_description,
            df=_CURRENT_DF,
        )
    except Exception as _ew_err:
        print(f"⚠️  execute.py writer failed (non-fatal): {_ew_err}")

    return json.dumps({
        "success": True,
        "function_name": function_name,
        "target_column": target_column,
        "code_auto_corrected": test_result.final_code != code,
        "code_tester_attempts": test_result.attempts,
        "result": test_result.result,
        "database_status": "Saved to SQLite (pending team approval)",
    }, default=str)

@tool
def execute_existing_function_with_params(function_name: str, params: dict) -> str:
    """
    Executes a pre-existing advanced data quality function (from Group 2 or Group 3)
    out of the database on the dataset.
    Requires passing specific `params` as a dictionary.
    Example: {"timestamp_col": "date_time", "window_minutes": 15}.
    Returns a JSON string with the result of the function execution.
    """
    global _CURRENT_DF
    if _CURRENT_DF is None:
        return "Error: No dataframe loaded."

    import sqlite3
    db_path = "database/app.db"   # single database — functions.db was legacy

    try:
        with sqlite3.connect(db_path, timeout=10.0) as conn:
            cursor = conn.cursor()
            cursor.execute(
                "SELECT function_code, function_description FROM data_quality_functions "
                "WHERE function_name = ? AND approved_by_team = 1",
                (function_name,),
            )
            row = cursor.fetchone()

            if not row:
                return json.dumps({
                    "success": False,
                    "error": f"Function '{function_name}' not found or not approved in the database.",
                })

            function_code, function_description = row[0], row[1] or ""

            # Execute code dynamically to define the function
            local_scope: dict = {}
            exec_globals = {
                "pd": pd,
                "np": __import__("numpy"),
                "Dict": Dict,
                "Any": Any,
                "List": List,
                "Optional": Optional,
            }
            exec(function_code, exec_globals, local_scope)

            if function_name not in local_scope:
                return json.dumps({
                    "success": False,
                    "error": f"Function '{function_name}' was not defined in the code body.",
                })

            func = local_scope[function_name]
            res = func(_CURRENT_DF, params)

            # ── Update execute.py ─────────────────────────────────────────
            try:
                from agents.execute_writer import append_existing_function_call
                append_existing_function_call(
                    function_name=function_name,
                    function_code=function_code,
                    params=params,
                    function_description=function_description,
                    df=_CURRENT_DF,
                )
            except Exception as _ew_err:
                print(f"⚠️  execute.py writer failed (non-fatal): {_ew_err}")

            return json.dumps({
                "success": True,
                "function_name": function_name,
                "params_used": params,
                "result": res,
            }, default=str)

    except Exception as e:
        return json.dumps({
            "success": False,
            "error": str(e),
        })


@tool
def run_analysis_script(script: str, question_summary: str = "") -> str:
    """
    Write and execute a COMPLETE Python analysis script against the full DataFrame.

    Use this tool for ANY follow-up question that requires data computation,
    statistics, filtering, or multi-column analysis.

    The script:
      - Receives `df` (the complete dataset — ALL columns are available)
      - May define helper functions and chain multiple operations together
      - MUST assign the final answer to:  RESULT = <dict or list>
      - RESULT must be JSON-serialisable (use float()/int() for numpy scalars,
        .to_dict() or .tolist() instead of DataFrames/arrays)

    The Code Testing Agent will automatically test and fix the script up to 3 times.
    On success, execute.py is completely rewritten with this script (previous
    session content is removed).

    Parameters
    ----------
    script          : Full Python script (may include helper functions).
                      Must end with RESULT = {...} or RESULT = [...]
    question_summary: Short label for the question (used in execute.py header).
    """
    global _CURRENT_DF
    if _CURRENT_DF is None:
        return "Error: No dataframe loaded. Please upload a dataset first."

    from agents.code_tester import test_and_fix_script
    test_result = test_and_fix_script(
        script=script,
        df=_CURRENT_DF,
        question=question_summary,
        verbose=True,
    )

    if not test_result.success:
        return json.dumps({
            "success": False,
            "question_summary": question_summary,
            "error": test_result.error,
            "tester_attempts": test_result.attempts,
            "message": (
                "The Code Testing Agent could not produce a working script after "
                f"{test_result.attempts} attempt(s). Please review the error and "
                "try a different approach."
            ),
        }, default=str)

    # ── Rewrite execute.py with the verified script ───────────────────────
    try:
        from agents.execute_writer import write_prompt_script
        write_prompt_script(
            script=test_result.final_code,
            question=question_summary,
            df=_CURRENT_DF,
        )
    except Exception as _ew_err:
        print(f"⚠️  execute.py writer failed (non-fatal): {_ew_err}")

    return json.dumps({
        "success": True,
        "question_summary": question_summary,
        "script_auto_corrected": test_result.final_code != script,
        "tester_attempts": test_result.attempts,
        "result": test_result.result,
    }, default=str)
