import pandas as pd
from typing import Any
from langchain_core.tools import tool
import json

# Global reference to the current dataframe for tools to use
# (In a production app, we would pass this dataframe via LangChain Runnable binding 
# or custom tool creation, but a global variable is simple for this script)
_CURRENT_DF = None

def set_current_df(df: pd.DataFrame):
    """Stores the active dataframe so the `pandas_query_tool` can query against it."""
    global _CURRENT_DF
    _CURRENT_DF = df

@tool
def generate_and_test_custom_function(function_name: str, code: str, target_column: str, function_description: str = "Autogenerated custom function.") -> str:
    """
    Generates a new data quality python function, tests it on a target column, and saves it to the database pending human approval.
    
    The python function MUST take a single argument `series` (which is a pd.Series) and return a Dictionary of stats or findings.
    You must provide the raw python code for the function in the `code` argument. Do not explain the code, just write exactly the function definition.
    You must provide a `function_description` briefly explaining what this check does.
    
    The function will be saved to the SQLite database with "approved_by_team=False" (0) and executed on the provided `target_column`.
    """
    global _CURRENT_DF
    if _CURRENT_DF is None:
        return "Error: No dataframe loaded."
    
    if target_column not in _CURRENT_DF.columns:
        return f"Error: '{target_column}' is not a valid column in the dataset."
        
    try:
        # Execute code dynamically to define the function in memory first to validate it
        local_scope = {}
        import pandas as pd
        from typing import Dict, Any
        exec_globals = {"pd": pd, "Dict": Dict, "Any": Any}
        exec(code, exec_globals, local_scope)
        
        if function_name not in local_scope:
            return f"Error: Function '{function_name}' was not defined in the provided code."
            
        func = local_scope[function_name]
        
        # Test it on the data
        series = _CURRENT_DF[target_column]
        result = func(series)
        
        # Save to database if test succeeds
        # Save the new valid function to database
        import sqlite3
        import datetime
        db_path = "database/app.db"
        now = datetime.datetime.now().isoformat()
        
        try:
            with sqlite3.connect(db_path, timeout=10.0) as conn:
                cursor = conn.cursor()
                cursor.execute('''
                INSERT INTO data_quality_functions
                (function_name, function_code, function_description, function_group, approved_by_team, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                ''', (
                    function_name, 
                    code, 
                    function_description, 
                    4,      # Group 4 for Agent Generated
                    False,  # Unapproved by default
                    now, 
                    now
                ))
        except sqlite3.IntegrityError:
            return json.dumps({
                "success": False,
                "error": f"Function name conflict: '{function_name}' already exists in the database. Please generate the function again using a different, UNIQUE name."
            })
        
        return json.dumps({
            "success": True,
            "target_column": target_column,
            "function_name": function_name,
            "result": result,
            "database_status": "Saved to SQLite (pending team approval)"
        }, default=str)
        
    except Exception as e:
        return json.dumps({
            "success": False,
            "error": str(e)
        })

@tool
def execute_existing_function_with_params(function_name: str, params: dict) -> str:
    """
    Executes a pre-existing advanced data quality function (from Group 2 or Group 3) out of the database on the dataset.
    Requires passing specific `params` as a dictionary. Example: {"timestamp_col": "date_time", "window_minutes": 15}.
    Returns a JSON string with the result of the function execution.
    """
    global _CURRENT_DF
    if _CURRENT_DF is None:
        return "Error: No dataframe loaded."
        
    import sqlite3
    db_path = "database/functions.db"
    
    try:
        with sqlite3.connect(db_path, timeout=10.0) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT function_code FROM data_quality_functions WHERE function_name = ?", (function_name,))
            result = cursor.fetchone()
            
            if not result:
                return f"Error: Function '{function_name}' not found in the database."
                
            function_code = result[0]
            
            # Execute code dynamically to define the function
            local_scope = {}
            import pandas as pd
            from typing import Dict, Any
            exec_globals = {"pd": pd, "Dict": Dict, "Any": Any}
            exec(function_code, exec_globals, local_scope)
            
            if function_name not in local_scope:
                return f"Error: Function '{function_name}' was not defined in the code body."
                
            func = local_scope[function_name]
            
            # Test it on the data
            res = func(_CURRENT_DF, params)
            return json.dumps({
                "success": True,
                "function_name": function_name,
                "params_used": params,
                "result": res
            }, default=str)
            
    except Exception as e:
        return json.dumps({
            "success": False,
            "error": str(e)
        })
